
version: '2'

services:
  db:
    container_name: jeedom_mysql
    restart: always
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_USER: 'jeedom'
      MYSQL_PASSWORD: 'jeedom'
      MYSQL_DATABASE: 'jeedom'
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"

  jeedom:
    container_name: jeedom_php
    restart: always
    image: jeedom/jeedom
    volumes:
      - ./volumes/www:/var/www
    ports:
      - "8022:22"
      - "8080:80"
    depends_on:
      - db
